feat: added dockerfile from edx-platform repo
edx/public-dockerfiles pull request #11
Opened 2024-10-09 10:32 UTC by huniafatima-arbi

2024-10-16 07:50 UTC, mfarhan943 commented on .github/workflows/push-edx-platform-images.yml
> +
It looks like the port values are incorrect. They should be the following:
```
    lms_dev: port 18000
    cms_dev: port 18010
    cms: port 8010
    lms: port 8000
```

2024-10-17 06:06 UTC, huniafatima-arbi commented on .github/workflows/push-edx-platform-images.yml
> +
The ports information is taken as mentioned in `Makefile` in `edx-platform` which was previously being used in image build and push. 
[Link to Makefile](https://github.com/openedx/edx-platform/blob/master/Makefile#L170)

2024-10-18 17:02 UTC, UsamaSadiq requested changes

2024-10-18 17:02 UTC, UsamaSadiq commented on dockerfiles/edx-platform.Dockerfile
> +FROM base as development
```suggestion
FROM base AS development
```

2024-10-21 14:56 UTC, UsamaSadiq approved these changes
Looks good to be merged but let's get @dianakhuang 's approval on this as well before merging.

2024-10-21 15:34 UTC, dianakhuang commented on .github/workflows/push-edx-platform-images.yml
> +
I am inclined to move it back to 8010 and 8000 for this. I think devstack does its own remapping for it.

2024-10-21 15:35 UTC, dianakhuang commented on .github/workflows/push-edx-platform-images.yml
> +    runs-on: ubuntu-20.04
Since we've been discussing this elsewhere, could we try moving this to 22.04?

2024-10-21 15:36 UTC, dianakhuang commented on dockerfiles/edx-platform.Dockerfile
> +# * Be a suitable base for production LMS and CMS images (THIS IS NOT YET THE CASE!).
Hmm, we might need to update these comments. I believe we are using them for edx.org event bus consumers.

2024-10-21 15:37 UTC, dianakhuang reviewed
I think this is mostly mergable with the exception of putting the ports back to what we were doing before.

2024-10-21 15:40 UTC, UsamaSadiq commented
> I think this is mostly mergable with the exception of putting the ports back to what we were doing before.

We couldn't identify what the usage of these ports are. Could you give us some context on why we are using different port addresses than the ones which are being used in local setup.

2024-10-21 16:06 UTC, dianakhuang commented
@UsamaSadiq To be honest, I don't know why it's doing that, but the fact that it's building both production and development files that way makes me a bit more cautious. If we want to switch it to the devstack ports and do thorough testing to find out what is counting on it, I'm okay with moving forward without switching them back.

2024-10-21 19:18 UTC, merged