Add workflow and dockerfile for edx-exams
edx/public-dockerfiles pull request #32
Opened 2024-10-14 09:49 UTC by mumarkhan999

**Related issue**
- https://github.com/edx/public-dockerfiles/issues/23

2024-10-15 13:06 UTC, mfarhan943 commented on .github/workflows/push-edx-exams-image.yaml
> +          body: Push Image to docker.io/edxops for registrar failed! For details see "github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
Push Image to docker.io/edxops for Edx Exams failed!

2024-10-22 12:30 UTC, UsamaSadiq requested changes

2024-10-22 12:30 UTC, UsamaSadiq commented on .github/workflows/push-edx-exams-image.yaml
> +  pull_request:
We need to remove this parameter before merging the PR.

2024-10-23 12:36 UTC, UsamaSadiq approved these changes

2024-10-23 12:36 UTC, merged