Add Dockerfile and workflow for course discovery
edx/public-dockerfiles pull request #9
Opened 2024-10-08 10:46 UTC by mfarhan943

**Description**
This PR adds Dockerfile and workflow to push the image for course discovery in the repo.

**Issue Link**
https://github.com/edx/public-dockerfiles/issues/4

2024-10-18 16:44 UTC, UsamaSadiq requested changes

2024-10-18 16:44 UTC, UsamaSadiq commented on .github/workflows/push-course-discovery-image.yaml
> +          to: team-cosmonauts@edx.org
Owning team for course-discovery is `phoenix`. We should ask the team if they have an email address available for tagging. If not then, let's ask them which email address they would like to be notified on for the failure notification.

2024-10-18 16:46 UTC, UsamaSadiq commented
@mfarhan943 since you have now write access to the repository, let's close this PR and create a PR by pushing the changes directly. 
Then we can also add `pull_request` header and test the build on the PR itself.

2024-10-22 08:03 UTC, mfarhan943 commented on .github/workflows/push-course-discovery-image.yaml
> +          to: team-cosmonauts@edx.org
I have updated the email in new PR.

2024-10-22 08:05 UTC, mfarhan943 commented
Closing this PR as a new PR with the direct branch has been opened.
https://github.com/edx/public-dockerfiles/pull/41

2024-10-22 08:05 UTC, closed without merging